/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Medication } from "./types";

export const PRESET_MEDICATIONS: Medication[] = [
  {
    id: "med-1",
    tradeName: "ნუროფენი ფორტე (Nurofen Forte)",
    genericName: "იბუპროფენი (Ibuprofen)",
    classificationDepartment: ["General", "ER/Resuscitation"],
    pharmacologicalGroup: "NSAID",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება წყალთან ერთად, არ საჭიროებს განზავებას.",
    frequency: "2x",
    mealConnection: "After",
    timeOfDay: ["Morning", "Evening"],
    indications: ["ტკივილი (Pain)", "ცხელება (Fever)", "ანთება (Inflammation)"],
    contraindications: ["CKD", "Pregnancy"],
    sideEffects: "დისპეფსია, კუჭის ლორწოვანის გაღიზიანება, თირკმლის ფუნქციის დაქვეითება ხანგრძლივი გამოყენებისას.",
    clinicalPearls: "სიფრთხილით თირკმლის ქრონიკული უკმარისობის დროს (იწვევს თირკმლის პერფუზიის შემცირებას).",
    isFavorite: true,
    price: 8.5,
    source: "PSP"
  },
  {
    id: "med-2",
    tradeName: "ამარილი (Amaryl)",
    genericName: "გლიმეპირიდი (Glimepiride)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "სულფონილშარდოვანა (Sulfonylurea)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "არ საჭიროებს განზავებას.",
    frequency: "1x",
    mealConnection: "Before meal",
    timeOfDay: ["Morning"],
    indications: ["შაქრიანი დიაბეტი ტიპი 2 (Type 2 Diabetes)"],
    contraindications: ["Pregnancy", "CKD"],
    sideEffects: "ჰიპოგლიკემია, წონაში მატება, ალერგიული რეაქციები.",
    clinicalPearls: "გამოიყენება საუზმის წინ. აუცილებელია ჰიპოგლიკემიის რისკის მონიტორინგი. eGFR < 30-ის დროს უკუნაჩვენებია.",
    isFavorite: true,
    price: 14.2,
    source: "Aversi"
  },
  {
    id: "med-3",
    tradeName: "დექსამეთაზონი (Dexamethasone)",
    genericName: "დექსამეთაზონი (Dexamethasone)",
    classificationDepartment: ["ER/Resuscitation", "Endocrinology", "Pediatrics"],
    pharmacologicalGroup: "გლუკოკორტიკოსტეროიდი (Glucocorticoid)",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "შეიძლება ვენაში ნელი ინფუზია (5% გლუკოზა ან ფიზიოლოგიური ხსნარი 10-20 წთ).",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["ანაფილაქსია (Anaphylaxis)", "მწვავე ასთმა (Acute Asthma)", "კრუპი (Croup)", "თავის ტვინის შეშუპება (Brain Edema)"],
    contraindications: ["Diabetes"],
    sideEffects: "ჰიპერგლიკემია, არტერიული ჰიპერტენზია, ოსტეოპოროზი, იმუნოსუპრესია.",
    clinicalPearls: "მკვეთრად ზრდის გლიკემიას! შაქრიანი დიაბეტის მქონე პაციენტებში საჭიროა ინსულინის დოზის კორექცია.",
    isFavorite: false,
    price: 4.8,
    source: "PSP"
  },
  {
    id: "med-4",
    tradeName: "ვეროშპირონი (Verospiron)",
    genericName: "სპირონოლაქტონი (Spironolactone)",
    classificationDepartment: ["Cardiology", "Endocrinology"],
    pharmacologicalGroup: "კალიუმის დამზოგველი დიურეტიკი (K-Sparing Diuretic)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება საკვებთან ერთად.",
    frequency: "1x",
    mealConnection: "During",
    timeOfDay: ["Morning"],
    indications: ["გულის უკმარისობა (Heart Failure)", "არტერიული ჰიპერტენზია (Hypertension)", "პირველადი ალდოსტერონიზმი"],
    contraindications: ["High Potassium", "CKD"],
    sideEffects: "ჰიპერკალიემია, გინეკომასტია (ხანგრძლივი მიღებისას), მენსტრუალური ციკლის დარღვევა.",
    clinicalPearls: "აკრძალულია კალიუმის მაღალი დონის (> 5.2 მმოლ/ლ) დროს! იწვევს კალიუმის შეკავებას ორგანიზმში.",
    isFavorite: true,
    price: 11.3,
    source: "Aversi"
  },
  {
    id: "med-5",
    tradeName: "დოპამინი (Dopamine Hydrocloride)",
    genericName: "დოპამინი (Dopamine)",
    classificationDepartment: ["ER/Resuscitation", "Cardiology"],
    pharmacologicalGroup: "კატექოლამინი / კარდიოტონული საშუალება",
    route: "IV",
    dosageForm: "Infusion",
    dilutionAdminRate: "განაზავეთ 200 მგ დოპამინი 250 მლ ფიზიოლოგიურ ხსნარში ან 5% დექსტროზაში. შეიყვანეთ მხოლოდ ინფუზომატით (ცენტრალური კათეტერით).",
    frequency: "Continuous Infusion",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["შოკი (Cardiogenic / Septic Shock)", "მწვავე ჰიპოტენზია (Severe Hypotension)"],
    contraindications: ["ფეოქრომოციტომა"],
    sideEffects: "ტაქიკარდია, არითმია, არტერიული ჰიპერტენზია, ქსოვილების ნეკროზი ექსტრავაზაციისას.",
    clinicalPearls: "LASA ALERT: არ აგერიოთ დობუტამინში! დოპამინს აქვს უფრო ძლიერი ვაზოპრესორული ეფექტი და ალფა-სტიმულაცია.",
    isFavorite: false,
    price: 5.6,
    source: "PSP"
  },
  {
    id: "med-6",
    tradeName: "დობუტრექსი (Dobutrex)",
    genericName: "დობუტამინი (Dobutamine)",
    classificationDepartment: ["ER/Resuscitation", "Cardiology"],
    pharmacologicalGroup: "სინთეზური სიმპათომიმეტიკი (Beta-1 Agonist)",
    route: "IV",
    dosageForm: "Infusion",
    dilutionAdminRate: "250 მგ განაზავეთ 250 მლ ფიზიოლოგიურ ხსნარში. შეიყვანეთ ინფუზიის სახით, დოზირება მკაცრად წონის მიხედვით.",
    frequency: "Continuous Infusion",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["მწვავე გულის უკმარისობა (Acute Heart Failure)", "კარდიოგენული შოკი (Cardiogenic Shock)"],
    contraindications: ["იდიოპათიური ჰიპერტროფიული სუბაორტული სტენოზი"],
    sideEffects: "არითმია, ტაქიკარდია, თავის ტკივილი, ჰიპოკალიემია.",
    clinicalPearls: "LASA ALERT: არ აგერიოთ დოპამინში! დობუტამინი ძირითადად ზრდის გულის განდევნის ფრაქციას ვაზოკონსტრიქციის გარეშე.",
    isFavorite: false,
    price: 32.0,
    source: "Aversi"
  },
  {
    id: "med-7",
    tradeName: "გლუკოფაჟი (Glucophage)",
    genericName: "მეტფორმინი (Metformin)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "ბიგუანიდი (Biguanide)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება ჭამის დროს ან ჭამის შემდეგ წყალთან ერთად.",
    frequency: "2x",
    mealConnection: "After",
    timeOfDay: ["Morning", "Evening"],
    indications: ["შაქრიანი დიაბეტი ტიპი 2 (Type 2 Diabetes)", "ინსულინრეზისტენტობა"],
    contraindications: ["CKD", "Liver Failure"],
    sideEffects: "გულისრევა, დიარეა, მეტალის გემო პირში, ლაქტატაციდოზი (იშვიათი მაგრამ მძიმე).",
    clinicalPearls: "უკუნაჩვენებია თუ eGFR < 30 მლ/წთ (ლაქტატაციდოზის მაღალი რისკი)! დოზა ნახევრდება eGFR 30-45-ის დროს.",
    isFavorite: true,
    price: 12.8,
    source: "PSP"
  },
  {
    id: "med-8",
    tradeName: "აუგმენტინი (Augmentin)",
    genericName: "ამოქსიცილინი + კლავულანის მჟავა (Amoxicillin + Clavulanic Acid)",
    classificationDepartment: ["General", "Pediatrics"],
    pharmacologicalGroup: "ბეტა-ლაქტამური ანტიბიოტიკი (Beta-lactam Antibiotic)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება ჭამის წინ კუჭ-ნაწლავის ტრაქტის მხრივ გვერდითი მოვლენების შესამცირებლად.",
    frequency: "2x",
    mealConnection: "Before meal",
    timeOfDay: ["Morning", "Evening"],
    indications: ["ბაქტერიული სინუსიტი", "პნევმონია", "შარდგამომყოფი გზების ინფექციები", "რბილი ქსოვილების ინფექციები"],
    contraindications: ["Penicillin Allergy"],
    sideEffects: "დიარეა, კანზე გამონაყარი, კანდიდოზი, ქოლესტაზური სიყვითლე.",
    clinicalPearls: "აბსოლუტურად უკუნაჩვენებია პენიცილინზე ალერგიის ანამნეზის მქონე პაციენტებში! ანაფილაქსიის რისკი.",
    isFavorite: false,
    price: 24.5,
    source: "Aversi"
  }
];

export const OFFLINE_EMERGENCY_CATALOG: Medication[] = [
  ...PRESET_MEDICATIONS,
  {
    id: "off-1",
    tradeName: "ლ-თიროქსინი (L-Thyroxine Berlin-Chemie)",
    genericName: "ლევოთიროქსინი (Levothyroxine)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "ფარისებრი ჯირკვლის ჰორმონი",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დილით უზმოზე, ჭამამდე 30 წუთით ადრე, მცირე რაოდენობით წყალთან ერთად.",
    frequency: "1x",
    mealConnection: "Before meal",
    timeOfDay: ["Morning"],
    indications: ["ჰიპოთირეოზი", "ეუთირეოიდული ჩიყვი", "ფარისებრი ჯირკვლის კიბოს შემდგომი თერაპია"],
    contraindications: [],
    sideEffects: "ტაქიკარდია, ნერვული აგზნებადობა, უძილობა, წონაში კლება, ჭარბი ოფლიანობა.",
    clinicalPearls: "მიღება უნდა მოხდეს მკაცრად უზმოზე. კალციუმის და რკინის პრეპარატები ამცირებენ მის შეწოვას (ინტერვალი მინიმუმ 4 სთ).",
    isFavorite: false,
    price: 10.2,
    source: "Aversi"
  },
  {
    id: "off-2",
    tradeName: "აქტრაპიდი HM (Actrapid HM)",
    genericName: "ინსულინი რეგულარი (Insulin Regular - ხსნადი ადამიანის ინსულინი)",
    classificationDepartment: ["Endocrinology", "ER/Resuscitation"],
    pharmacologicalGroup: "მოკლე მოქმედების ინსულინი",
    route: "SC",
    dosageForm: "Ampoule",
    dilutionAdminRate: "ვენაში შეყვანისას (ER) განაზავეთ ფიზიოლოგიურ ხსნარში 1:1 თანაფარდობით (მაგ: 50 სე 50 მლ ფიზხსნარში). კანქვეშ კეთდება ჭამამდე 30 წთ ადრე.",
    frequency: "3x",
    mealConnection: "Before meal",
    timeOfDay: ["Morning", "Noon", "Evening"],
    indications: ["შაქრიანი დიაბეტი ტიპი 1", "დიაბეტური კეტოაციდოზი (DKA)", "ჰიპერკალიემია (გლუკოზასთან ერთად)"],
    contraindications: [],
    sideEffects: "ჰიპოგლიკემია, ლიპოდისტროფია ინექციის ადგილას, ალერგიული რეაქციები.",
    clinicalPearls: "ერთადერთი ინსულინია, რომლის შეყვანაც შესაძლებელია როგორც კანქვეშ, ისე ინტრავენურად (კრიტიკულ მდგომარეობებში).",
    isFavorite: false,
    price: 28.4,
    source: "PSP"
  },
  {
    id: "off-3",
    tradeName: "კორდარონი (Cordarone)",
    genericName: "ამიოდარონი (Amiodarone)",
    classificationDepartment: ["ER/Resuscitation", "Cardiology"],
    pharmacologicalGroup: "III კლასის ანტიარითმული საშუალება",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "ER: 300 მგ განზავებული 20 მლ 5% გლუკოზაში ნელა 5 წთ განმავლობაში. არ განაზავოთ ფიზიოლოგიურ ხსნარში!",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["პარკუჭოვანი ტაქიკარდია", "პარკუჭების ფიბრილაცია", "მოციმციმე არითმიის პაროქსიზმი"],
    contraindications: ["Pregnancy", "Liver Failure"],
    sideEffects: "ფარისებრი ჯირკვლის დისფუნქცია (ამიოდარონ-ინდუცირებული), ფილტვის ფიბროზი, ჰეპატოტოქსიკურობა, QT ინტერვალის გახანგრძლივება.",
    clinicalPearls: "შეიცავს იოდს, შეუძლია გამოიწვიოს როგორც ჰიპო-, ისე ჰიპერთირეოზი. ვენაში შეყვანა ხდება მხოლოდ 5%-იან გლუკოზაში.",
    isFavorite: false,
    price: 18.5,
    source: "Aversi"
  },
  {
    id: "off-4",
    tradeName: "ადრენალინი (Adrenaline Hydrochloride)",
    genericName: "ეპინეფრინი (Epinephrine)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "ალფა- და ბეტა-ადრენომიმეტიკი",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "ანაფილაქსიისას: 0.3-0.5 მგ კუნთში (განუზავებელი). გულის გაჩერებისას: 1 მგ IV ყოველ 3-5 წუთში (განზავებული 10 მლ ფიზხსნარში).",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["ანაფილაქსიური შოკი", "გულის გაჩერება (ასისტოლია/ფიბრილაცია)", "მწვავე ლარინგოსპაზმი"],
    contraindications: [],
    sideEffects: "არტერიული ჰიპერტენზია, პარკუჭოვანი არითმია, ტაქიკარდია, ძლიერი შიში და კანკალი.",
    clinicalPearls: "გადაუდებელი მედიცინის პირველი რიგის წამალი ანაფილაქსიის დროს. კანქვეშა შეყვანა არ არის რეკომენდებული სისხლძარღვთა სპაზმის გამო.",
    isFavorite: false,
    price: 1.5,
    source: "PSP"
  },
  {
    id: "off-5",
    tradeName: "ატროპინის სულფატი (Atropine Sulfate)",
    genericName: "ატროპინი (Atropine)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "მ-ქოლინობლოკატორი",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "ბრადიკარდია: 0.5 მგ ვენაში ყოველ 3-5 წუთში მაქსიმუმ 3 მგ-მდე. ფოსფორორგანული მოწამვლა: 2 მგ ვენაში ატროპინიზაციის ნიშნებამდე.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["სიმპტომური ბრადიკარდია", "ავ-ბლოკადა", "ფოსფორორგანული ნაერთებით მოწამვლა", "ნერწყვდენის შემცირება პრეანესთეზიისას"],
    contraindications: [],
    sideEffects: "მიდრიაზი, პირის სიმშრალე, შარდის შეკავება, ტაქიკარდია, ჰალუცინაციები.",
    clinicalPearls: "სიფრთხილით გლაუკომის და წინამდებარე ჯირკვლის ჰიპერპლაზიის დროს. ეფექტურია ბრადიკარდიის კორექციისთვის.",
    isFavorite: false,
    price: 1.2,
    source: "Aversi"
  },
  {
    id: "off-6",
    tradeName: "ნორადრენალინი (Noradrenaline)",
    genericName: "ნორეპინეფრინი (Norepinephrine)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "ალფა-ადრენომიმეტიკი / ვაზოპრესორი",
    route: "IV",
    dosageForm: "Infusion",
    dilutionAdminRate: "4 მგ ნორადრენალინი განაზავეთ 250 მლ 5% გლუკოზაში. შეიყვანეთ მხოლოდ ცენტრალური ვენური კათეტერით ინფუზომატის მეშვეობით.",
    frequency: "Continuous Infusion",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["კარდიოგენული შოკი", "სეპტიური შოკი", "მწვავე ჰიპოტენზია რეფრაქტერული სითხეებით თერაპიის მიმართ"],
    contraindications: [],
    sideEffects: "ქსოვილის ნეკროზი ექსტრავაზაციისას, თირკმლის იშემია, არითმია, თავის ტკივილი.",
    clinicalPearls: "პირველი რიგის ვაზოპრესორი სეპტიური შოკის დროს. აუცილებელია ინტრავენური ზონის მუდმივი კონტროლი იშემიის თავიდან ასაცილებლად.",
    isFavorite: false,
    price: 45.0,
    source: "PSP"
  },
  {
    id: "off-7",
    tradeName: "ნიტროგლიცერინი (Nitroglycerin)",
    genericName: "ნიტროგლიცერინი (Nitroglycerin)",
    classificationDepartment: ["ER/Resuscitation", "Cardiology"],
    pharmacologicalGroup: "ორგანული ნიტრატი / ვაზოდილატატორი",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "ენისქვეშ 0.5 მგ ტაბლეტი. არ გადაყლაპოთ. შეიძლება განმეორდეს 5 წთ ინტერვალით 3 ტაბლეტამდე.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["სტენოკარდიის შეტევა (Angina)", "მარცხენაპარკუჭოვანი მწვავე უკმარისობა / ფილტვის შეშუპება"],
    contraindications: [],
    sideEffects: "მწვავე თავის ტკივილი, ჰიპოტენზია, ტაქიკარდია, სახის სიწითლე.",
    clinicalPearls: "კატეგორიულად უკუნაჩვენებია სილდენაფილის (ვიაგრა) მიღებიდან 24 საათში კრიტიკული ჰიპოტენზიის რისკის გამო.",
    isFavorite: false,
    price: 5.4,
    source: "Aversi"
  },
  {
    id: "off-8",
    tradeName: "ლაზიქსი (Lasix)",
    genericName: "ფუროსემიდი (Furosemide)",
    classificationDepartment: ["ER/Resuscitation", "Cardiology"],
    pharmacologicalGroup: "მარყუჟოვანი დიურეტიკი (Loop Diuretic)",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "ვენაში შეჰყავთ ნელა 20-40 მგ. სიჩქარე არ უნდა აღემატებოდეს 4 მგ/წთ ოტოტოქსიკურობის თავიდან ასაცილებლად.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["ფილტვის შეშუპება", "თავის ტვინის შეშუპება", "ჰიპერტონული კრიზი", "გულის/თირკმლის უკმარისობით გამოწვეული შეშუპება"],
    contraindications: ["CKD"],
    sideEffects: "ჰიპოკალიემია, ჰიპონატრიემია, დეჰიდრატაცია, ოტოტოქსიკურობა (მაღალი დოზებისას).",
    clinicalPearls: "აქტიურად გამოდევნის კალიუმს. აკრძალულია გამოხატული ჰიპოკალიემიის დროს. თირკმლის მწვავე უკმარისობისას საჭიროა სიფრთხილე.",
    isFavorite: false,
    price: 3.5,
    source: "PSP"
  },
  {
    id: "off-9",
    tradeName: "კალიუმის ქლორიდი 4% (Potassium Chloride 4%)",
    genericName: "კალიუმის ქლორიდი (K+)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "კალიუმის პრეპარატი კორექციისთვის",
    route: "IV",
    dosageForm: "Infusion",
    dilutionAdminRate: "ვენაში წვეთოვნად მხოლოდ განზავებული სახით! 20-40 მმოლ KCl 500 მლ ფიზხსნარში. შეყვანის სიჩქარე მაქსიმუმ 10 მმოლ/სთ.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Evening"],
    indications: ["გამოხატული ჰიპოკალიემია (< 3.0 მმოლ/ლ)", "დიგოქსინით მოწამვლის კომპლექსური თერაპია"],
    contraindications: ["High Potassium", "CKD"],
    sideEffects: "ვენის გაღიზიანება, ტკივილი ინექციისას, ჰიპერკალიემია, გულის გაჩერება სწრაფი შეყვანისას.",
    clinicalPearls: "კრიტიკული უსაფრთხოების წესი: არასდროს შეიყვანოთ კალიუმის ქლორიდი ნაკადით (IV bolus) — ეს იწვევს მყისიერ ასისტოლიას!",
    isFavorite: false,
    price: 2.1,
    source: "Aversi"
  },
  {
    id: "off-10",
    tradeName: "მაგნიუმის სულფატი 25% (Magnesium Sulfate)",
    genericName: "მაგნიუმის სულფატი (MgSO4)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "კალციუმის ანტაგონისტი / კრუნჩხვის საწინააღმდეგო",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "ეკლამფსია: 4 გ IV ნელა 10-15 წთ განმავლობაში, შემდეგ შემანარჩუნებელი წვეთოვანი. Torsades de Pointes: 1-2 გ 5% გლუკოზაში 5 წთ-ში.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["ეკლამფსია და მძიმე პრეეკლამფსია ორსულებში", "Torsades de Pointes ტიპის არითმია", "მძიმე ჰიპომაგნიემია"],
    contraindications: ["CKD"],
    sideEffects: "სუნთქვის დათრგუნვა, ჰიპოტენზია, კუნთოვანი ჰიპოტონია, რეფლექსების გაქრობა.",
    clinicalPearls: "ეკლამფსიის დროს პირველი რიგის წამალია. ჭარბი დოზირებისას ანტიდოტია კალციუმის გლუკონატი.",
    isFavorite: false,
    price: 3.2,
    source: "PSP"
  },
  {
    id: "off-11",
    tradeName: "კალციუმის გლუკონატი 10% (Calcium Gluconate)",
    genericName: "კალციუმის გლუკონატი (Ca2+)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "კალციუმის პრეპარატი",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "10 მლ 10% ხსნარი ვენაში ნელა 5-10 წთ-ის განმავლობაში, სასურველია ეკგ კონტროლით.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["მწვავე სიმპტომური ჰიპოკალციემია", "ჰიპერკალიემიის დროს მიოკარდიუმის დაცვა", "მაგნიუმის სულფატის ანტიდოტი"],
    contraindications: ["High Potassium"],
    sideEffects: "სიცხის შეგრძნება, ტაქიკარდია, სწრაფი შეყვანისას გულის გაჩერება.",
    clinicalPearls: "იცავს გულს ჰიპერკალიემიით გამოწვეული არითმიებისგან, თუმცა არ ამცირებს უშუალოდ კალიუმის დონეს სისხლში.",
    isFavorite: false,
    price: 2.8,
    source: "Aversi"
  },
  {
    id: "off-12",
    tradeName: "ჰეპარინი (Heparin Sodium)",
    genericName: "ჰეპარინი (Heparin)",
    classificationDepartment: ["ER/Resuscitation", "Cardiology"],
    pharmacologicalGroup: "პირდაპირი მოქმედების ანტიკოაგულანტი",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "ვენაში ბოლუსი 5000 სე, შემდეგ უწყვეტი ინფუზია ინფუზომატით, აპტტ-ს (aPTT) მკაცრი კონტროლით.",
    frequency: "Continuous Infusion",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["მწვავე კორონარული სინდრომი (ACS)", "ფილტვის არტერიის თრომბოემბოლია (PE)", "ღრმა ვენების თრომბოზი"],
    contraindications: ["Pregnancy"],
    sideEffects: "სისხლდენა, ჰეპარინ-ინდუცირებული თრომბოციტოპენია (HIT), ოსტეოპოროზი (ხანგრძლივი მიღებისას).",
    clinicalPearls: "ჭარბი დოზირებისას ანტიდოტია პროტამინის სულფატი. კანქვეშა შეყვანისას კეთდება მუცლის წინა კედელში.",
    isFavorite: false,
    price: 18.0,
    source: "PSP"
  },
  {
    id: "off-13",
    tradeName: "ნალოქსონი (Naloxone Hydrochloride)",
    genericName: "ნალოქსონი (Naloxone)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "ოპიოიდური რეცეპტორების ანტაგონისტი",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "0.4-2 მგ ვენაში, კუნთში ან კანქვეშ. შეიძლება განმეორდეს ყოველ 2-3 წუთში სუნთქვის აღდგენამდე.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["ოპიოიდური ანალგეტიკებით (ჰეროინი, მორფინი) ზედოზირება და სუნთქვის დათრგუნვა"],
    contraindications: [],
    sideEffects: "მწვავე აბსტინენციის სინდრომი, ტაქიკარდია, ჰიპერტენზია, პირღებინება.",
    clinicalPearls: "ნახევრადგამოყოფის პერიოდი უფრო მოკლეა, ვიდრე ოპიოიდების უმეტესობის, ამიტომ პაციენტს შეიძლება ხელახლა დაეწყოს აპნოე.",
    isFavorite: false,
    price: 6.5,
    source: "Aversi"
  },
  {
    id: "off-14",
    tradeName: "სიბაზონი (Sibazon / Diazepam)",
    genericName: "დიაზეპამი (Diazepam)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "ბენზოდიაზეპინი / ანქსიოლიტიკური, კრუნჩხვის საწინააღმდეგო",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "კრუნჩხვისას: 10 მგ ვენაში ნელა (მინიმუმ 2 წთ). არ განაზავოთ, პირდაპირ შეიყვანეთ მსხვილ ვენაში.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Bedtime"],
    indications: ["ეპილეფსიური სტატუსი", "მწვავე ფსიქომოტორული აგზნება", "ალკოჰოლური აბსტინენცია / დელირიუმი"],
    contraindications: ["Pregnancy"],
    sideEffects: "ძილიანობა, სუნთქვის დათრგუნვა (განსაკუთრებით ალკოჰოლთან ერთად), ჰიპოტენზია, დამოკიდებულება.",
    clinicalPearls: "სწრაფი შეყვანისას ვენაში იზრდება აპნოეს და ლარინგოსპაზმის რისკი. იქონიეთ მზადყოფნა ხელოვნური სუნთქვისთვის.",
    isFavorite: false,
    price: 5.2,
    source: "PSP"
  },
  {
    id: "off-15",
    tradeName: "ამლოდიპინი (Amlodipine)",
    genericName: "ამლოდიპინი (Amlodipine)",
    classificationDepartment: ["Cardiology", "General"],
    pharmacologicalGroup: "კალციუმის არხების ბლოკატორი (დიჰიდროპირიდინული)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დამოუკიდებლად საკვებისგან, დღეში ერთხელ, სასურველია საღამოს.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Evening"],
    indications: ["არტერიული ჰიპერტენზია", "სტაბილური სტენოკარდია", "პრინცმეტალის ვაზოსპასტიური სტენოკარდია"],
    contraindications: [],
    sideEffects: "პერიფერიული შეშუპება (განსაკუთრებით კოჭების), თავის ტკივილი, სახის სიწითლე, თავბრუსხვევა.",
    clinicalPearls: "კოჭების შეშუპება არის ხშირი და უსაფრთხო გვერდითი მოვლენა, არ საჭიროებს დიურეტიკების დანიშვნას.",
    isFavorite: false,
    price: 6.8,
    source: "Aversi"
  },
  {
    id: "off-16",
    tradeName: "კაპოტენი (Capoten)",
    genericName: "კაპტოპრილი (Captopril)",
    classificationDepartment: ["ER/Resuscitation", "Cardiology"],
    pharmacologicalGroup: "აგფ ინჰიბიტორი (ACE Inhibitor)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "ჰიპერტონული კრიზისას: 25-50 მგ ტაბლეტი ენის ქვეშ (სუბლინგვალურად) სწრაფი ეფექტისთვის.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Evening"],
    indications: ["არტერიული ჰიპერტენზია", "ჰიპერტონული კრიზი", "გულის ქრონიკული უკმარისობა"],
    contraindications: ["Pregnancy", "CKD"],
    sideEffects: "მშრალი ხველა, ჰიპერკალიემია, თირკმლის ფუნქციის გაუარესება, ანგიონევროზული შეშუპება (იშვიათი).",
    clinicalPearls: "იდეალურია კრიზების სწრაფი მართვისთვის ენისქვეშა მიღებისას. უკუნაჩვენებია ორსულებში (ტერატოგენულია!).",
    isFavorite: false,
    price: 4.5,
    source: "PSP"
  },
  {
    id: "off-17",
    tradeName: "ბეტალოკ ზოკი (Betaloc Zok)",
    genericName: "მეტოპროლოლი სუცინატი (Metoprolol)",
    classificationDepartment: ["Cardiology", "General"],
    pharmacologicalGroup: "სელექციური ბეტა-1 ბლოკატორი",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დილით, ტაბლეტი არ უნდა დაიღეჭოს, მთლიანად უნდა გადაიყლაპოს.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["არტერიული ჰიპერტენზია", "გულის ქრონიკული უკმარისობა", "ტაქიკარდია", "მიოკარდიუმის ინფარქტის შემდგომი პერიოდი"],
    contraindications: [],
    sideEffects: "ბრადიკარდია, დაღლილობა, ცივი კიდურები, ბრონქოსპაზმი (იშვიათად, მაგრამ შესაძლებელია), ერექციული დისფუნქცია.",
    clinicalPearls: "მეტოპროლოლი სუცინატი არის ხანგრძლივი მოქმედების, განსხვავებით ტარტრატისგან. არ შეიძლება მკვეთრი მოხსნა (რიკოშეტული ტაქიკარდია).",
    isFavorite: false,
    price: 19.4,
    source: "Aversi"
  },
  {
    id: "off-18",
    tradeName: "დიაბეტონ MR (Diabeton MR)",
    genericName: "გლიკლაზიდი (Gliclazide)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "მეორე თაობის სულფონილშარდოვანა",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება საუზმის დროს, მთლიანად, წყალთან ერთად.",
    frequency: "1x",
    mealConnection: "During",
    timeOfDay: ["Morning"],
    indications: ["შაქრიანი დიაბეტი ტიპი 2", "მიკროსისხლძარღვოვანი გართულებების პრევენცია"],
    contraindications: ["Pregnancy", "CKD"],
    sideEffects: "ჰიპოგლიკემია, წონაში მატება, ქოლესტაზური სიყვითლე.",
    clinicalPearls: "სულფონილშარდოვანას ჯგუფიდან აქვს ჰიპოგლიკემიის შედარებით დაბალი რისკი. უკუნაჩვენებია თირკმლის მძიმე უკმარისობისას.",
    isFavorite: false,
    price: 16.5,
    source: "PSP"
  },
  {
    id: "off-19",
    tradeName: "იანუვია (Januvia)",
    genericName: "სიტაგლიპტინი (Sitagliptin)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "DPP-4 ინჰიბიტორი (გლიპტინი)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დამოუკიდებლად საკვებისგან, დღის ნებისმიერ დროს.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["შაქრიანი დიაბეტი ტიპი 2 (გლიკემიის კონტროლი)"],
    contraindications: ["Pregnancy"],
    sideEffects: "ნაზოფარინგიტი, თავის ტკივილი, იშვიათად მწვავე პანკრეატიტი, სახსრების ტკივილი.",
    clinicalPearls: "არ იწვევს ჰიპოგლიკემიას და წონაში მატებას. საჭიროა დოზის კორექცია თირკმლის ზომიერი/მძიმე უკმარისობისას.",
    isFavorite: false,
    price: 42.8,
    source: "Aversi"
  },
  {
    id: "off-20",
    tradeName: "ფორქსიგა (Forxiga)",
    genericName: "დაპაგლიფლოზინი (Dapagliflozin)",
    classificationDepartment: ["Endocrinology", "Cardiology"],
    pharmacologicalGroup: "SGLT-2 ინჰიბიტორი (გლიფლოზინი)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დღეში ერთხელ, საკვებისგან დამოუკიდებლად, სასურველია დღის პირველ ნახევარში.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["შაქრიანი დიაბეტი ტიპი 2", "გულის უკმარისობა შემცირებული განდევნის ფრაქციით (HFrEF)", "თირკმლის ქრონიკული დაავადება"],
    contraindications: ["Pregnancy"],
    sideEffects: "შარდსასქესო გზების ინფექციები, პოლიურია, დეჰიდრატაცია, იშვიათად ევგლიკემიური დიაბეტური კეტოაციდოზი.",
    clinicalPearls: "უნიკალური პრეპარატია, რომელიც იცავს თირკმელს და გულს. აძლიერებს გლუკოზურიას, ამიტომ საჭიროა ჰიგიენის მკაცრი დაცვა.",
    isFavorite: false,
    price: 54.0,
    source: "PSP"
  },
  {
    id: "off-21",
    tradeName: "ჯარდიანსი (Jardiance)",
    genericName: "ემპაგლიფლოზინი (Empagliflozin)",
    classificationDepartment: ["Endocrinology", "Cardiology"],
    pharmacologicalGroup: "SGLT-2 ინჰიბიტორი (გლიფლოზინი)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დილით, დამოუკიდებლად ჭამისგან.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["შაქრიანი დიაბეტი ტიპი 2", "გულის უკმარისობა (ნებისმიერი განდევნის ფრაქციით)", "კარდიოვასკულური სიკვდილობის შემცირება"],
    contraindications: ["Pregnancy"],
    sideEffects: "ვაგინალური კანდიდოზი, შარდდენის გახშირება, არტერიული ჰიპოტენზია.",
    clinicalPearls: "აქვს უძლიერესი მტკიცებულება გულ-სისხლძარღვთა სიკვდილობის შემცირებაზე დიაბეტიან პაციენტებში. eGFR < 20-ზე არ ინიშნება.",
    isFavorite: false,
    price: 56.5,
    source: "Aversi"
  },
  {
    id: "off-22",
    tradeName: "ვიქტოზა (Victoza)",
    genericName: "ლირაგლუტიდი (Liraglutide)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "GLP-1 რეცეპტორების აგონისტი",
    route: "SC",
    dosageForm: "Ampoule",
    dilutionAdminRate: "კანქვეშა ინექცია მუცელში, ბარძაყში ან მხარში, დღეში ერთხელ, საკვების მიღებისგან დამოუკიდებლად.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["შაქრიანი დიაბეტი ტიპი 2", "წონის კლება (მაღალი დოზებისას - Saxenda)"],
    contraindications: ["Pregnancy"],
    sideEffects: "გულისრევა, პირღებინება, დიარეა, მადის დაკარგვა, პანკრეატიტი (იშვიათად).",
    clinicalPearls: "ინექცია კეთდება კალმით. იცავს კარდიოვასკულურ სისტემას და ხელს უწყობს წონის მნიშვნელოვან კლებას. უკუნაჩვენებია მედულარული თირეოიდული კარცინომის ანამნეზისას.",
    isFavorite: false,
    price: 160.0,
    source: "PSP"
  },
  {
    id: "off-23",
    tradeName: "ოზემპიკი (Ozempic)",
    genericName: "სემაგლუტიდი (Semaglutide)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "GLP-1 რეცეპტორების აგონისტი (კვირაში ერთხელ)",
    route: "SC",
    dosageForm: "Ampoule",
    dilutionAdminRate: "კანქვეშა ინექცია კვირაში ერთხელ, ერთსა და იმავე დღეს, დღის ნებისმიერ მონაკვეთში.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["შაქრიანი დიაბეტი ტიპი 2", "კარდიოვასკულური რისკების შემცირება", "წონის კლება"],
    contraindications: ["Pregnancy"],
    sideEffects: "გულისრევა, ყაბზობა ან დიარეა, გასტროპარეზი, ნაღვლის ბუშტის კენჭები.",
    clinicalPearls: "უახლესი და უაღრესად პოპულარული პრეპარატი. კვირაში ერთხელ მიღება მკვეთრად ზრდის პაციენტის დამყოლობას. იწყება 0.25 მგ-ით კვირაში.",
    isFavorite: false,
    price: 250.0,
    source: "Aversi"
  },
  {
    id: "off-24",
    tradeName: "ნოვორაპიდი (NovoRapid)",
    genericName: "ინსულინი ასპარტი (Insulin Aspart - ულტრამოკლე მოქმედების)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "ანალოგური მოკლე მოქმედების ინსულინი",
    route: "SC",
    dosageForm: "Ampoule",
    dilutionAdminRate: "კეთდება კანქვეშ უშუალოდ ჭამის წინ (0-15 წთ) ან ჭამის დაწყებიდან მალევე.",
    frequency: "3x",
    mealConnection: "Before meal",
    timeOfDay: ["Morning", "Noon", "Evening"],
    indications: ["შაქრიანი დიაბეტი ტიპი 1 და ტიპი 2 (პრანდიალური გლიკემიის კონტროლი)"],
    contraindications: [],
    sideEffects: "ჰიპოგლიკემია, ლიპოჰიპერტროფია, ალერგიული რეაქციები.",
    clinicalPearls: "მოქმედებას იწყებს 10-20 წუთში, ამიტომ არ საჭიროებს ხანგრძლივ ლოდინს ჭამამდე, რაც ამცირებს მოულოდნელი ჰიპოგლიკემიის რისკს.",
    isFavorite: false,
    price: 35.5,
    source: "PSP"
  },
  {
    id: "off-25",
    tradeName: "ლანტუსი (Lantus SoloStar)",
    genericName: "ინსულინი გლარგინი (Insulin Glargine - ხანგრძლივი ბაზალური)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "ულტრახანგრძლივი ბაზალური ინსულინი",
    route: "SC",
    dosageForm: "Ampoule",
    dilutionAdminRate: "კანქვეშა ინექცია დღეში ერთხელ, მკაცრად ერთსა და იმავე დროს (სასურველია ძილის წინ).",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Bedtime"],
    indications: ["ბაზალური ინსულინთერაპია შაქრიანი დიაბეტი ტიპი 1 და 2 დროს"],
    contraindications: [],
    sideEffects: "ჰიპოგლიკემია, ინექციის ადგილის ტკივილი, ლიპოდისტროფია.",
    clinicalPearls: "მოქმედებს 24 საათის განმავლობაში 'პიკის გარეშე' (flat profile), რაც მკვეთრად ამცირებს ღამის ჰიპოგლიკემიების რისკს.",
    isFavorite: false,
    price: 85.0,
    source: "Aversi"
  },
  {
    id: "off-26",
    tradeName: "ჰუმალოგი (Humalog)",
    genericName: "ინსულინი ლისპრო (Insulin Lispro - ულტრამოკლე)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "ულტრამოკლე მოქმედების ადამიანის ინსულინის ანალოგი",
    route: "SC",
    dosageForm: "Ampoule",
    dilutionAdminRate: "კანქვეშ ჭამამდე 15 წთ-ით ადრე ან ჭამის დროს.",
    frequency: "3x",
    mealConnection: "Before meal",
    timeOfDay: ["Morning", "Noon", "Evening"],
    indications: ["შაქრიანი დიაბეტი ტიპი 1 და ტიპი 2 მკურნალობა"],
    contraindications: [],
    sideEffects: "ჰიპოგლიკემია, წონაში მატება, ქავილი.",
    clinicalPearls: "მოქმედების ხანგრძლივობაა 2-5 საათი. იდეალურია პრანდიალური (საჭმლის შემდგომი) პიკების სამართავად.",
    isFavorite: false,
    price: 36.0,
    source: "PSP"
  },
  {
    id: "off-27",
    tradeName: "ტრესიბა (Tresiba)",
    genericName: "ინსულინი დეგლუდეკი (Insulin Degludec - ზეხანგრძლივი)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "ზეხანგრძლივი ბაზალური ინსულინი (მოქმედებს 42 სთ-ზე მეტხანს)",
    route: "SC",
    dosageForm: "Ampoule",
    dilutionAdminRate: "კანქვეშ დღეში ერთხელ, მოქნილი დროის რეჟიმით (საჭიროებისას მიღების ინტერვალი შეიძლება შეიცვალოს).",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Bedtime"],
    indications: ["ბაზალური ინსულინთერაპია ტიპი 1 და ტიპი 2 შაქრიანი დიაბეტის დროს"],
    contraindications: [],
    sideEffects: "ჰიპოგლიკემია, ლოკალური რეაქციები.",
    clinicalPearls: "აქვს მოქმედების რეკორდული ხანგრძლივობა (42+ საათი) და მინიმალური დღიური ვარიაბელობა. ღამის ჰიპოგლიკემიის ყველაზე დაბალი მაჩვენებელი.",
    isFavorite: false,
    price: 110.0,
    source: "Aversi"
  },
  {
    id: "off-28",
    tradeName: "ჯენტადუეტო (Jentadueto)",
    genericName: "ლინაგლიპტინი + მეტფორმინი (Linagliptin + Metformin)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "კომბინირებული ორალური ჰიპოგლიკემიური საშუალება",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება ჭამის დროს კუჭ-ნაწლავის ტრაქტის მხრივ გვერდითი მოვლენების შესამცირებლად.",
    frequency: "2x",
    mealConnection: "During",
    timeOfDay: ["Morning", "Evening"],
    indications: ["შაქრიანი დიაბეტი ტიპი 2 ორმაგი თერაპია"],
    contraindications: ["CKD", "Liver Failure"],
    sideEffects: "ლაქტატაციდოზი, დიარეა, მუცლის ტკივილი, ვიტამინ B12 დეფიციტი ხანგრძლივი გამოყენებისას.",
    clinicalPearls: "ლინაგლიპტინის კომპონენტი უსაფრთხოა თირკმლისთვის, თუმცა მეტფორმინის არსებობის გამო პრეპარატი მაინც იზღუდება eGFR < 30 მლ/წთ-ზე.",
    isFavorite: false,
    price: 49.5,
    source: "PSP"
  },
  {
    id: "off-29",
    tradeName: "გალვუს მეტი (Galvus Met)",
    genericName: "ვილდაგლიპტინი + მეტფორმინი (Vildagliptin + Metformin)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "ორმაგი ორალური ანტიდიაბეტური საშუალება",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "ტაბლეტი მიიღება საკვებთან ერთად დილით და საღამოს.",
    frequency: "2x",
    mealConnection: "During",
    timeOfDay: ["Morning", "Evening"],
    indications: ["შაქრიანი დიაბეტი ტიპი 2, როდესაც მეტფორმინის მონოთერაპია არაეფექტურია"],
    contraindications: ["CKD", "Liver Failure"],
    sideEffects: "მეტეორიზმი, გულისრევა, თავბრუსხვევა, ღვიძლის ფერმენტების ტრანზიტორული მატება.",
    clinicalPearls: "მეტფორმინისა და DPP-4 ინჰიბიტორის პოპულარული და ძალიან ეფექტური კომბინაცია. აუცილებელია თირკმლის ფუნქციის კონტროლი.",
    isFavorite: false,
    price: 38.2,
    source: "Aversi"
  },
  {
    id: "off-30",
    tradeName: "ეუთიროქსი (Euthyrox)",
    genericName: "ლევოთიროქსინი (Levothyroxine Sodium)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "თიროიდული ჰორმონის ანალოგი",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დილით უზმოზე, ჭამამდე 30 წუთით ადრე, მხოლოდ წყალთან ერთად.",
    frequency: "1x",
    mealConnection: "Before meal",
    timeOfDay: ["Morning"],
    indications: ["ჰიპოთირეოზი", "დიფუზური ტოქსიკური ჩიყვის ოპერაციის შემდგომი შემცვლელი თერაპია"],
    contraindications: [],
    sideEffects: "არითმია, ტრემორი, თავის ტკივილი, წონაში კლება.",
    clinicalPearls: "ზუსტი დოზირება კრიტიკულია (ტაბლეტები მოდის 25, 50, 75, 88, 100, 112, 125, 137, 150 მკგ). TSH კონტროლი ხდება ყოველ 6-8 კვირაში.",
    isFavorite: false,
    price: 9.8,
    source: "PSP"
  },
  {
    id: "off-31",
    tradeName: "პროპილთიოურაცილი (Propylthiouracil / PTU)",
    genericName: "პროპილთიოურაცილი (Propylthiouracil)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "ანტითიროიდული საშუალება / თირეოსტატიკი",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება ყოველ 8 საათში ერთხელ, საკვებისგან დამოუკიდებლად.",
    frequency: "3x",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening"],
    indications: ["ჰიპერთირეოზი", "გრეივსის დაავადება", "თირეოტოქსიკური კრიზი"],
    contraindications: ["Liver Failure"],
    sideEffects: "მძიმე ჰეპატოტოქსიურობა (ღვიძლის მწვავე ნეკროზი), აგრანულოციტოზი, კანის გამონაყარი, სახსრების ტკივილი.",
    clinicalPearls: "პირველი არჩევანის პრეპარატია ორსულობის I ტრიმესტრში (თიროზოლის ნაცვლად), თუმცა სხვა დროს ერიდებიან ღვიძლის ტოქსიკურობის გამო.",
    isFavorite: false,
    price: 34.0,
    source: "Aversi"
  },
  {
    id: "off-32",
    tradeName: "თიროზოლი (Thyrozol)",
    genericName: "თიამაზოლი / მეთიმაზოლი (Thiamazole)",
    classificationDepartment: ["Endocrinology"],
    pharmacologicalGroup: "ანტითიროიდული პრეპარატი (Antithyroid)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება ჭამის შემდეგ, ტაბლეტები იყლაპება მთლიანად საკმარისი რაოდენობის წყალთან ერთად.",
    frequency: "1x",
    mealConnection: "After",
    timeOfDay: ["Morning"],
    indications: ["თირეოტოქსიკოზი", "ჰიპერთირეოზის კონსერვატიული მკურნალობა", "რადიოაქტიური იოდით თერაპიისთვის მომზადება"],
    contraindications: ["Pregnancy"],
    sideEffects: "ალერგიული დერმატიტი, აგრანულოციტოზი (კრიტიკული!), ქოლესტაზი, წონაში მატება.",
    clinicalPearls: "პაციენტს უნდა ვურჩიოთ, რომ ყელის ტკივილისა და ცხელების დაწყებისთანავე სასწრაფოდ შეწყვიტოს წამალი და გაიკეთოს სისხლის საერთო ანალიზი აგრანულოციტოზის გამოსარიცხად.",
    isFavorite: false,
    price: 15.5,
    source: "PSP"
  },
  {
    id: "off-33",
    tradeName: "სოლუ-კორტეფი (Solu-Cortef)",
    genericName: "ჰიდროკორტიზონი (Hydrocortisone Sodium Succinate)",
    classificationDepartment: ["ER/Resuscitation", "Endocrinology"],
    pharmacologicalGroup: "გლუკოკორტიკოიდი (Glucocorticoid - სწრაფი მოქმედების)",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "აღდგენილი ხსნარი შეიყვანეთ ვენაში ნაკადით ან წვეთოვნად. კრიზისას: 100 მგ IV ბოლუსი, შემდეგ 100-200 მგ დღე-ღამეში.",
    frequency: "3x",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening"],
    indications: ["თირკმელზედა ჯირკვლის მწვავე უკმარისობა (Addisonian Crisis)", "მძიმე ალერგიული რეაქციები და ანაფილაქსია", "სტატუს ასთმატიკუსი"],
    contraindications: [],
    sideEffects: "ნატრიუმის და სითხის შეკავება, ჰიპოკალიემია, არტერიული ჰიპერტენზია, მწვავე ფსიქოზი.",
    clinicalPearls: "თირკმელზედა ჯირკვლის კრიზის დროს სასიცოცხლოდ მნიშვნელოვანია ჰიდროკორტიზონის დაუყოვნებლივ შეყვანა მინერალოკორტიკოიდული აქტივობის გამო.",
    isFavorite: false,
    price: 12.0,
    source: "Aversi"
  },
  {
    id: "off-34",
    tradeName: "სოლუ-მედროლი (Solu-Medrol)",
    genericName: "მეთილპრედნიზოლონი (Methylprednisolone)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "სისტემური გლუკოკორტიკოსტეროიდი (მაღალაქტიური)",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "პულს-თერაპია: 250-1000 მგ IV წვეთოვნად 30-60 წთ-ის განმავლობაში 5% გლუკოზაში ან ფიზხსნარში.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["გაფანტული სკლეროზის მწვავე შეტევა", "მძიმე რევმატოიდული გამწვავება", "ზურგის ტვინის მწვავე ტრავმა", "ანაფილაქსიური შოკი"],
    contraindications: ["Diabetes"],
    sideEffects: "მკვეთრი ჰიპერგლიკემია, კუჭის მწვავე წყლული სისხლდენით, ოსტეონეკროზი.",
    clinicalPearls: "აქვს ძლიერი ანთების საწინააღმდეგო ეფექტი და ნაკლები წყალ-მარილოვანი შეკავება, ვიდრე ჰიდროკორტიზონს. ზრდის გლიკემიას მკვეთრად.",
    isFavorite: false,
    price: 35.8,
    source: "PSP"
  },
  {
    id: "off-35",
    tradeName: "ვენტოლინი (Ventolin)",
    genericName: "სალბუტამოლი (Salbutamol)",
    classificationDepartment: ["ER/Resuscitation", "Pediatrics"],
    pharmacologicalGroup: "მოკლე მოქმედების ბეტა-2 აგონისტი (SABA)",
    route: "PO",
    dosageForm: "Syrup",
    dilutionAdminRate: "ინჰალატორიდან 1-2 შესხურება (100-200 მკგ) ბრონქოსპაზმის კუპირებისთვის. ER-ში ნებულაიზერით: 2.5-5 მგ ნებულაში ფიზხსნართან ერთად.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["ბრონქული ასთმის შეტევა", "ბრონქოსპაზმი ფილტვის ქრონიკული ობსტრუქციული დაავადებისას (COPD)"],
    contraindications: [],
    sideEffects: "ტრემორი (კანკალი კიდურების), ტაქიკარდია, ჰიპოკალიემია, თავის ტკივილი.",
    clinicalPearls: "ჭარბი გამოყენება მიანიშნებს ასთმის არაკონტროლირებად მიმდინარეობაზე. ნებულაიზერით ინჰალაციისას შეუძლია გამოიწვიოს კალიუმის დონის კლება სისხლში.",
    isFavorite: false,
    price: 9.4,
    source: "Aversi"
  },
  {
    id: "off-36",
    tradeName: "პრედნიზოლონი (Prednisolone)",
    genericName: "პრედნიზოლონი (Prednisolone)",
    classificationDepartment: ["Endocrinology", "Pediatrics", "General"],
    pharmacologicalGroup: "სისტემური გლუკოკორტიკოსტეროიდი",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დილით საუზმის შემდეგ (კუჭის ლორწოვანის დასაცავად), ტაბლეტი წყალთან ერთად.",
    frequency: "1x",
    mealConnection: "After",
    timeOfDay: ["Morning"],
    indications: ["აუტოიმუნური დაავადებები", "ბრონქული ასთმა მძიმე ფორმა", "თირკმელზედა ჯირკვლის ქრონიკული უკმარისობა"],
    contraindications: ["Diabetes"],
    sideEffects: "კუშინგოიდური სინდრომი (სახის გაპუტკუნება), იმუნოსუპრესია, არტერიული ჰიპერტენზია, ოსტეოპოროზი.",
    clinicalPearls: "პრეპარატის მოხსნა უნდა მოხდეს ეტაპობრივად (დოზის ნელი შემცირებით) თირკმელზედა ჯირკვლის მწვავე უკმარისობის თავიდან ასაცილებლად.",
    isFavorite: false,
    price: 6.2,
    source: "PSP"
  },
  {
    id: "off-37",
    tradeName: "ატარაქსი (Atarax)",
    genericName: "ჰიდროქსიზინი (Hydroxyzine)",
    classificationDepartment: ["General", "Pediatrics"],
    pharmacologicalGroup: "პირველი თაობის ანტიჰისტამინური / ანქსიოლიტიკი",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "ტაბლეტი მიიღება ჭამისგან დამოუკიდებლად, საღამოს ძილის წინ ძლიერი სედატიური ეფექტის გამო.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Bedtime"],
    indications: ["შფოთვა და დაძაბულობა", "ქავილი დერმატიტების დროს", "პრემედიკაცია ქირურგიული ჩარევის წინ"],
    contraindications: [],
    sideEffects: "ძილიანობა, პირის სიმშრალე, ყაბზობა, QT ინტერვალის გახანგრძლივება.",
    clinicalPearls: "აქვს გამოხატული სედატიური და ანქსიოლიტიკური ეფექტი. არ გამოიყენება ხანდაზმულებში გამოხატული ანტიქოლინერგული გვერდითი ეფექტების გამო (ლუდის კრიტერიუმები).",
    isFavorite: false,
    price: 18.2,
    source: "Aversi"
  },
  {
    id: "off-38",
    tradeName: "ვერაპამილი (Verapamil Hydrochloride)",
    genericName: "ვერაპამილი (Verapamil)",
    classificationDepartment: ["Cardiology"],
    pharmacologicalGroup: "არადიჰიდროპირიდინული კალციუმის არხების ბლოკატორი (IV კლასის ანტიარითმული)",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "ვენაში შეყვანა: 5-10 მგ ნელა 2 წუთის განმავლობაში ეკგ-ს და არტერიული წნევის მუდმივი კონტროლით.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["სუპრავენტრიკულური პაროქსიზმული ტაქიკარდია", "მოციმციმე არითმიის დროს პარკუჭოვანი სიხშირის კონტროლი", "არტერიული ჰიპერტენზია"],
    contraindications: [],
    sideEffects: "მკვეთრი ბრადიკარდია, ჰიპოტენზია, ყაბზობა (ხშირი ორალური მიღებისას), ავ-ბლოკადა.",
    clinicalPearls: "კატეგორიულად აკრძალულია ბეტა-ბლოკერებთან ერთად ვენაში ერთდროულად შეყვანა — ამან შეიძლება გამოიწვიოს სრული ავ-ბლოკადა და გულის გაჩერება!",
    isFavorite: false,
    price: 8.9,
    source: "PSP"
  },
  {
    id: "off-39",
    tradeName: "ასპირინი კარდიო (Aspirin Cardiox)",
    genericName: "აცეტილსალიცილის მჟავა (Acetylsalicylic Acid)",
    classificationDepartment: ["Cardiology", "General"],
    pharmacologicalGroup: "ანტიაგრეგანტი / არასტეროიდული ანთების საწინააღმდეგო",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დღეში ერთხელ ჭამის შემდეგ, წყალთან ერთად. ტაბლეტი დაფარულია ნაწლავში ხსნადი გარსით.",
    frequency: "1x",
    mealConnection: "After",
    timeOfDay: ["Evening"],
    indications: ["მიოკარდიუმის ინფარქტის მეორადი პრევენცია", "იშემიური ინსულტის პრევენცია", "არასტაბილური სტენოკარდია"],
    contraindications: ["Pregnancy"],
    sideEffects: "კუჭის ლორწოვანის გაღიზიანება, მიკროსისხლდენა კუჭ-ნაწლავის ტრაქტიდან, ასპირინული ასთმა.",
    clinicalPearls: "კარდიოპროტექციული მიზნით გამოიყენება დაბალი დოზებით (75-100 მგ). მწვავე ინფარქტის ეჭვისას პირველი ტაბლეტი (300 მგ) პაციენტმა უნდა დაღეჭოს სწრაფი ეფექტისთვის.",
    isFavorite: false,
    price: 3.8,
    source: "Aversi"
  },
  {
    id: "off-40",
    tradeName: "პლავიქსი (Plavix)",
    genericName: "კლოპიდოგრელი (Clopidogrel)",
    classificationDepartment: ["Cardiology"],
    pharmacologicalGroup: "ანტიაგრეგანტი (P2Y12 ინჰიბიტორი)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დღეში ერთხელ, საკვებისგან დამოუკიდებლად, ერთსა და იმავე დროს.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["ათეროთრომბული გართულებების პრევენცია", "მწვავე კორონარული სინდრომი", "კორონარული სტენტირების შემდგომი ორმაგი ანტიაგრეგანტული თერაპია"],
    contraindications: [],
    sideEffects: "სისხლდენა, ჰემატომები, დისპეფსია, კანზე გამონაყარი.",
    clinicalPearls: "ხშირად ინიშნება ასპირინთან ერთად სტენტირებიდან 12 თვის განმავლობაში. სიფრთხილით პაციენტებში, რომლებსაც უტარდებათ ქირურგიული ჩარევა (საჭიროა მოხსნა ოპერაციამდე 5 დღით ადრე).",
    isFavorite: false,
    price: 48.5,
    source: "PSP"
  },
  {
    id: "off-41",
    tradeName: "კლექსანი (Clexane)",
    genericName: "ენოქსაპარინი (Enoxaparin Sodium - დაბალმოლეკულური ჰეპარინი)",
    classificationDepartment: ["Cardiology", "ER/Resuscitation"],
    pharmacologicalGroup: "დაბალმოლეკულური ჰეპარინი (LMWH)",
    route: "SC",
    dosageForm: "Ampoule",
    dilutionAdminRate: "მზა შპრიცი კანქვეშა ინექციისთვის. კეთდება მუცლის კედელში. არ გამოუშვათ ჰაერის ბუშტუკი შპრიციდან ინექციამდე.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["ღრმა ვენების თრომბოზის მკურნალობა და პროფილაქტიკა", "მწვავე კორონარული სინდრომი", "თრომბოემბოლიის პრევენცია ქირურგიული ოპერაციებისას"],
    contraindications: [],
    sideEffects: "სისხლდენა, ჰემატომა ინექციის ადგილას, თრომბოციტოპენია (ნაკლებად, ვიდრე უფრაქციო ჰეპარინისას).",
    clinicalPearls: "არ საჭიროებს aPTT-ს მუდმივ კონტროლს, რაც აადვილებს ბინაზე გამოყენებას. დოზირება ხდება მკაცრად სხეულის წონის მიხედვით.",
    isFavorite: false,
    price: 32.4,
    source: "Aversi"
  },
  {
    id: "off-42",
    tradeName: "დიგოქსინი (Digoxin)",
    genericName: "დიგოქსინი (Digoxin)",
    classificationDepartment: ["Cardiology"],
    pharmacologicalGroup: "გულის გლიკოზიდი (Cardiac Glycoside)",
    route: "PO",
    dosageForm: "Tablet",
    dilutionAdminRate: "მიიღება დღეში ერთხელ, პულსის სიხშირის კონტროლით. არ მიიღოთ თუ პულსი < 60/წთ.",
    frequency: "1x",
    mealConnection: "Independent",
    timeOfDay: ["Morning"],
    indications: ["გულის ქრონიკული უკმარისობა ტაქისისტოლური მოციმციმე არითმიით"],
    contraindications: ["High Potassium"],
    sideEffects: "დიგოქსინური ტოქსიკურობა (გულისრევა, ყვითელი ხედვა, არითმიები, ბრადიკარდია), ჰიპოკალიემია აძლიერებს ტოქსიკურობას.",
    clinicalPearls: "აქვს ძალიან ვიწრო თერაპიული ფანჯარა. ჰიპოკალიემია მკვეთრად ზრდის დიგოქსინით ინტოქსიკაციის რისკს, ამიტომ კალიუმის დონე უნდა იყოს მკაცრად კონტროლირებული.",
    isFavorite: false,
    price: 6.2,
    source: "PSP"
  },
  {
    id: "off-43",
    tradeName: "ლიდოკაინი 2% (Lidocaine Hydrochloride)",
    genericName: "ლიდოკაინი (Lidocaine)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "Iბ კლასის ანტიარითმული საშუალება / ადგილობრივი საანესთეზიო",
    route: "IV",
    dosageForm: "Ampoule",
    dilutionAdminRate: "IV ბოლუსი: 1-1.5 მგ/კგ ვენაში, შემდეგ შემანარჩუნებელი წვეთოვანი ინფუზია 1-4 მგ/წთ სიჩქარით.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["პარკუჭოვანი არითმიები მიოკარდიუმის ინფარქტის დროს", "ადგილობრივი გაუტკივარება"],
    contraindications: [],
    sideEffects: "ნევროლოგიური სიმპტომები (კრუნჩხვა, სმენის გაუარესება, თავბრუსხვევა), ბრადიკარდია, ჰიპოტენზია.",
    clinicalPearls: "ანტიარითმული მიზნით გამოიყენება მხოლოდ პარკუჭოვანი არითმიებისას, აბსოლუტურად უეფექტოა წინაგულოვანი არითმიების დროს.",
    isFavorite: false,
    price: 1.8,
    source: "Aversi"
  },
  {
    id: "off-44",
    tradeName: "ნატრიუმის ბიკარბონატი 4% (Sodium Bicarbonate 4%)",
    genericName: "ნატრიუმის ბიკარბონატი (NaHCO3)",
    classificationDepartment: ["ER/Resuscitation"],
    pharmacologicalGroup: "ელექტროლიტური ხსნარი აციდოზის კორექციისთვის",
    route: "IV",
    dosageForm: "Infusion",
    dilutionAdminRate: "ვენაში წვეთოვნად, შეყვანის სიჩქარე და დოზირება გამოითვლება სისხლის აირების და ბაზისური დეფიციტის (BE) მიხედვით.",
    frequency: "PRN",
    mealConnection: "Independent",
    timeOfDay: ["Morning", "Noon", "Evening", "Bedtime"],
    indications: ["მძიმე მეტაბოლური აციდოზი", "ტრიციკლური ანტიდეპრესანტებით ზედოზირება", "ჰიპერკალიემია"],
    contraindications: [],
    sideEffects: "მეტაბოლური ალკალოზი, ჰიპოკალიემია, ნატრიუმის ჭარბი დატვირთვა, შეშუპება.",
    clinicalPearls: "ჰიპერკალიემიის მართვისას ხელს უწყობს კალიუმის გადასვლას უჯრედშიდა სივრცეში, რითაც დროებით ამცირებს მის კონცენტრაციას სისხლში.",
    isFavorite: false,
    price: 4.2,
    source: "PSP"
  }
];
